### ISSUE TITLE
Google Cloud bucket not working

### ISSUE THREAD

**Issue by mirfan899** [unicamp-dl/mMARCO#8] opened 2021-11-23 06:53 UTC
I tried to download the data from give link, but It seems data is not there and I'm getting this error message.
![mmarco](https://user-images.githubusercontent.com/3822565/142981741-0ca2ac67-e0f5-4389-9d7a-247eeea6dfbc.png)

**Comment by seanmacavaney** [comment] 2021-11-28 14:20
I’m having the same problem.

**Comment by seanmacavaney** [comment] 2021-11-28 20:58
EDIT: Note: now that the files are hosted elsewhere (see #10), these links are no longer active.

@mirfan899, I don't want to host these files perpetually, but I have the original files temporarily mirrored here if you need them:

language | file | md5 hash
----------|----|-----------
de | [docs](https://macavaney.us/files/mmarco/b0d40bb296c3ec903926243e8397560e) | `b0d40bb296c3ec903926243e8397560e`
de | [queries/train](https://macavaney.us/files/mmarco/711b9e9c2163fe07468d6303bbf038f8) | `711b9e9c2163fe07468d6303bbf038f8`
de | [queries/dev](https://macavaney.us/files/mmarco/8d6383b34cd332f5f21c70c3e6a97579) | `8d6383b34cd332f5f21c70c3e6a97579`
es | [docs](https://macavaney.us/files/mmarco/c82d3e5998f4cefb5a730a337680fac0) | `c82d3e5998f4cefb5a730a337680fac0`
es | [queries/train](https://macavaney.us/files/mmarco/676e7011d020383422556d2c4b39b67d) | `676e7011d020383422556d2c4b39b67d`
es | [queries/dev](https://macavaney.us/files/mmarco/1359d9516bf5dd9bf732012a25e7f536) | `1359d9516bf5dd9bf732012a25e7f536`
fr | [docs](https://macavaney.us/files/mmarco/941a8e717efb1ab74b9017976c08f73a) | `941a8e717efb1ab74b9017976c08f73a`
fr | [queries/train](https://macavaney.us/files/mmarco/4c9f45b9c7497d6efb44e593d2f5af4d) | `4c9f45b9c7497d6efb44e593d2f5af4d`
fr | [queries/dev](https://macavaney.us/files/mmarco/a86c46314a0abfb090c542e672bb66e2) | `a86c46314a0abfb090c542e672bb66e2`
id | [docs](https://macavaney.us/files/mmarco/5e9fd243bfcf160a1177c898796ae53e) | `5e9fd243bfcf160a1177c898796ae53e`
id | [queries/train](https://macavaney.us/files/mmarco/e74bc49a64adf32d105eeace23dc1a58) | `e74bc49a64adf32d105eeace23dc1a58`
id | [queries/dev](https://macavaney.us/files/mmarco/3d5f2261edb985d4fe052ed9e379a42a) | `3d5f2261edb985d4fe052ed9e379a42a`
it | [docs](https://macavaney.us/files/mmarco/c87e107fdd99f78a8789c984c96f3e46) | `c87e107fdd99f78a8789c984c96f3e46`
it | [queries/train](https://macavaney.us/files/mmarco/2aa7e48decfbfbaa327aa01f0d16bc3f) | `2aa7e48decfbfbaa327aa01f0d16bc3f`
it | [queries/dev](https://macavaney.us/files/mmarco/d9df4b10d892288c81611e7ed74e1549) | `d9df4b10d892288c81611e7ed74e1549`
pt | [docs](https://macavaney.us/files/mmarco/77260081f0332befa6aa3e6c922b8fb9) | `77260081f0332befa6aa3e6c922b8fb9`
pt | [queries/train](https://macavaney.us/files/mmarco/df2ed4ef0bdb93405ba276a92530fc03) | `df2ed4ef0bdb93405ba276a92530fc03`
pt | [queries/dev](https://macavaney.us/files/mmarco/262ce189e3d57059b2795c16db44bb81) | `262ce189e3d57059b2795c16db44bb81`
ru | [docs](https://macavaney.us/files/mmarco/27f64ca50b1862d285c53a1bcdc26793) | `27f64ca50b1862d285c53a1bcdc26793`
ru | [queries/train](https://macavaney.us/files/mmarco/e4c09d563124569a632780c3ed1179b2) | `e4c09d563124569a632780c3ed1179b2`
ru | [queries/dev](https://macavaney.us/files/mmarco/4d803553d69f967764360570c3e66c84) | `4d803553d69f967764360570c3e66c84`
zh | [docs](https://macavaney.us/files/mmarco/d5672e88206038d8a3d261987b3bd788) | `d5672e88206038d8a3d261987b3bd788`
zh | [queries/train](https://macavaney.us/files/mmarco/21649d058877379bc8184923ab8ec408) | `21649d058877379bc8184923ab8ec408`
zh | [queries/dev](https://macavaney.us/files/mmarco/83820cac1d3e27a7c911d5116ebce558) | `83820cac1d3e27a7c911d5116ebce558`

**Comment by rodrigonogueira4** [comment] 2021-11-28 23:56
Hi @mirfan899 @seanmacavaney, sorry, we are migrating to another storage and the files should be available in a few days. Sorry for the inconvenience.

**Comment by mirfan899** [comment] 2021-11-29 05:53
Thanks.

**Comment by seanmacavaney** [comment] 2021-12-12 14:15
bump - any updates on this?

**Comment by rodrigonogueira4** [comment] 2021-12-13 16:18
Sorry about this taking longer than we expected. [This PR](https://github.com/unicamp-dl/mMARCO/pull/10
) contains the new link for the translated datasets: https://huggingface.co/datasets/unicamp-dl/mmarco/tree/main/data/v1.1

In the next couple of days, we will release a new version with better translations, with an improvement of 3-4 points in MRR@10. Stay tuned!

**Comment by seanmacavaney** [comment] 2021-12-13 18:32
Thanks! Are you planning to make the v1.0 data available too somewhere for, e.g., those who want to reproduce the results from the original paper or other comparisons folks may want to make between the versions?

**Comment by lhbonifacio** [comment] 2021-12-13 19:01
Hi @seanmacavaney . As @rodrigonogueira4 mentioned, the v1.1 data is the one available on [this PR](https://github.com/unicamp-dl/mMARCO/pull/10).
The upcoming v2.1 data will be released soon.

**Comment by seanmacavaney** [comment] 2021-12-13 19:19
Thanks for the clarification about the forthcoming v2.1. It looks like the v1.1 still differs from the original release of the data though in a few cases, which could impact one's ability to reproduce the Chinese and Portugese results from the original paper.

file | v1.0 md5 | v1.1 md5
---|---|---
chinese_queries.dev.tsv | `83820cac1d3e27a7c911d5116ebce558` | `9ea0d3e92aaf87d65c07c297893d0ff6`
portuguese_queries.dev.tsv | `262ce189e3d57059b2795c16db44bb81` | `4210db124ff1e3b7c803b9cb666c5e44`
portuguese_queries.train.tsv | `df2ed4ef0bdb93405ba276a92530fc03` | `c253c476ff1ad1d51bae169cea180acd`

(For all the other files, the md5s remained unchanged between v1.0 and v1.1.)

It looks like for Chinese, in some cases there were missing translations, which were changed from empty strings to ".". For Portuguese, the translations look rather different-- was a different translation model used?

Thanks!

**Comment by lhbonifacio** [comment] 2021-12-13 19:42
@seanmacavaney Indeed we have some differences in `queries.dev` and `queries.train` files.
In some case, we manually corrected some issue on these translated files. 
However, as far as we know, these fixes did not cause any impact on  reproducing the original results from our paper. 
The 6980 queries from `queries.dev.small` evaluation set were not affected.
We are finishing the PR with all the translated data along with each BM25 run file, so it is possible to achieve the same results.

**Comment by seanmacavaney** [comment] 2021-12-13 19:44
Great- thanks!

**Comment by lhbonifacio** [comment] 2022-01-11 13:52
Closing this issue as the mMARCO is now available on [HF datasets](https://huggingface.co/datasets/unicamp-dl/mmarco).

**Closed as completed by lhbonifacio** 2022-01-11 13:52 UTC

**Comment by seanmacavaney** [comment] 2022-01-11 13:58
Great, thanks @lhbonifacio! I've added v1, the slightly-revised v1.1, and v2 to ir-datasets as well here: https://ir-datasets.com/master/mmarco.html

**Comment by rodrigonogueira4** [comment] 2022-01-11 14:00
@seanmacavaney Awesome!

**Comment by cramraj8** [comment] 2023-01-04 18:16
@seanmacavaney , do you have Arabic data mirrored somewhere that I can use ? Thanks in advance!

**Comment by seanmacavaney** [comment] 2023-01-04 19:23
Hey @cramraj8,

Arabic was introduced in v2 of the dataset, and the data seem to be available from the authors:

| language | file | md5 hash |
| ----------|-------|-------|
| ar | [docs](https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/google/collections/arabic_collection.tsv) | `b73406ce3a3d31edea240603d031be7a` |
| ar | [queries/dev](https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/google/queries/dev/arabic_queries.dev.tsv) | `d93efe298008c35389afacb3d9fedb06` |
| ar | [queries/train](https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/google/queries/train/arabic_queries.train.tsv) | `08ab9eed247819db2f1f013f7e06f0d6` |

If you'd rather use a toolkit to access the data instead of working with the raw files, it's available in the [ir-datasets package](https://ir-datasets.com/) under `mmarco/v2/ar`, `mmarco/v2/ar/train`, and `mmarco/v2/ar/dev`. E.g.,:

```python
import ir_datasets
dataset = ir_datasets.load("mmarco/v2/ar/dev")
for doc in dataset.docs:
    doc # namedtuple<doc_id, text>
for query in dataset.queries:
    query # namedtuple<query_id, text>
for qrel in dataset.qrels:
    qrel # namedtuple<query_id, doc_id, relevance, iteration>
```

Or in [HuggingFace datasets](https://huggingface.co/docs/datasets/index) under `unicamp-dl/mmarco` (see access instructions here: https://huggingface.co/datasets/unicamp-dl/mmarco)

Hope this helps!

**Comment by cramraj8** [comment] 2023-01-05 01:02
Thanks @seanmacavaney for your prompt reply. Downloading using HuggingFace datasets works well! Thank you!!
